### PR TITLE
Permit specifying the target commit of a release

### LINKED ISSUE #44: Feature: Allow specifying the target commit when creating a release
Currently, chart-releaser uses the default release creation behavior:  target commits for a new release will be the current commit on the default branch.  

This is reasonable default behavior, but it would be nice to have the ability to specify the commit.  Use cases - if you are doing backfill or other manual work outside of normal workflow.

### PR DESCRIPTION
**Pull request by travisgroth**
Closes #44

### CODE REVIEW

**Comment by travisgroth** [comment]
@unguiculus @scottrigby any feedback on this?

**Comment by scottrigby** [comment]
Hi @travisgroth thanks for your patience:

This PR branch has conflicts that must be resolved

Based on #44 it sounds like this would help address the use case where someone wants to create older chart releases based on previous chart version that exist in git history. Essentially:
1. look through git history in chart(s) Chart.yaml to find commit for desired chart versions
1. run upload command, passing in `commit` for each previous version you want to release
1. when finished, re-index

**Comment by travisgroth** [comment]
> Based on #44 it sounds like this would help address the use case where someone wants to create older chart releases based on previous chart version(s) that exist in git history. Essentially these steps:
> 
> 1. look through git history in chart(s) Chart.yaml to find commit for desired chart versions
> 2. run upload command, passing in `commit` for each previous version you want to release
> 3. when finished, re-index
> 
> Does that sound right?

Yep that's what I was trying to do at the time.  We were moving charts from `helm/stable` to an independent repo and wanted to retain our release history going back a few versions.  I imagine you'll have more folks looking to do this as they make the same move.  I used my branch to facilitate it successfully.

> This PR branch has conflicts that must be resolved before it can be merged

Done!

**Comment by travisgroth** [comment]
@scottrigby anything else on this?

**Pull request merged**
