### PR TITLE
add pre-release flag on upload command

### PR DESCRIPTION
**Pull request by pete911**
We would like to have an option to mark chart release as pre-release so we have more control.
- first we publish charts to github pages and mark release as pre release
- when we test the release we un-tick pre-release, this is picked up by github action that copies the charts to "prod" chart repo

### CODE REVIEW

**Comment by scottrigby** [comment]
Hi @pete911 thanks for this PR!
Interesting use case.
I wonder how this might be able to work with the wrapping helm/chart-releaer-action. Do you use that at all?
Your PR commit needs DCO, see https://github.com/helm/chart-releaser/pull/145/checks?check_run_id=4169306243

**Comment by pete911** [comment]
thanks @scottrigby, DCO should be fine now. I have tried the github action, but the problem with action was that it wanted to create a tag. Our workflow is like this:
- check if helm chart version changed on push to main
- create a git tag with the same version
- build and push images with this version
- package charts, generate index, ...

We use one version that is the same for docker image, git tag, chart version, ... It is less flexible but easier to manage (we know that this means components were tested together and they work)

**Comment by pete911** [comment]
Any news on this?

**Review by cpanato — COMMENTED** [review]
it looks good to me.
maybe add a test when the prerelease is true

**Comment by pete911** [comment]
@cpanato unit tests are updated with pre-release flag as well

**Comment by pete911** [comment]
Hi, this has been done since 10of November, is this going to be merged or should we just fork and create our own version?

**Pull request closed without merging**
