### PR TITLE
Peform single push on upload in case of multiple releases

### PR DESCRIPTION
**Pull request by amalgamm**
Resolves the problem [mentioned](https://github.com/helm/chart-releaser/pull/123#discussion_r1148913202) in [this](https://github.com/helm/chart-releaser/pull/123) PR

Lets say you want to upload more than one release and place it near the index file. After the first push your second push will be rejected with an error "Updates were rejected because a pushed branch tip is behind its remote". So either you need to pull changes before push another release or push all releases once in the end of upload action.

In case of pulling changes and pushing every release separately you'll face github will launch as many "pages build and deployment" actions as there are new releases you want to upload. All except one will be canceled, but the list of actions will look like a mess.

So the most efficient way is to make single push in the end of upload.

### CODE REVIEW

**Comment by gaelgatelement** [comment]
I just realized that my PR is a duplicate of this one, and this one is better as it fixes the tests. https://github.com/helm/chart-releaser/pull/336

Can we have someone take a look at this PR please ?

**Comment by cpanato** [comment]
does anyone can provide some manual tests on this? @amalgamm @gaelgatelement and show the logs and maybe the ci job

**Comment by cpanato** [comment]
thanks @gaelgatelement 
@amalgamm can you rebase and fix the lint issues?

**Comment by cpanato** [comment]
tested on my side and seems to work fine :)

**Comment by ibice** [comment]
Hi! I just run into the issue this PR fixes, it'd be cool to have it merged!

**Comment by amalgamm** [comment]
@cpanato I think I fixed the lint. Sorry it took so long

**Comment by cpanato** [comment]
Did you test the case with `PackagesWithIndex` set as well? not sure if will change any behavior

**Comment by amalgamm** [comment]
> Did you test the case with `PackagesWithIndex` set as well? not sure if will change any behavior

I didn't but I think this case is covered by tests

**Comment by jbrandli** [comment]
please merge

**Comment by marquesj2-ppb** [comment]
Any way to get this merged?

**Comment by 0xThresh** [comment]
Sorry to tag again @cpanato but I'm running into the described issue as well and am hoping to see this merged. Thank you!

**Comment by cpanato** [comment]
i did a test using the latest chart-release and two chart update and i see one push: https://github.com/cpanato/testing-ci-providers/actions/runs/9764682879/job/26953586398

**Comment by KrisJohnstone** [comment]
Bump.

**Comment by stephaneetje** [comment]
Hello, does this PR have any chance to get merge anytime ??

**Comment by OddKMS** [comment]
Adding my voice to this - would really like to see this get merged so that our Helm Chart repo can function properly with multiple charts.

**Review by cpanato — APPROVED** [review]
thanks!

**Comment by cpanato** [comment]
will be good if someone uses the chart-releaser from main and confirm this is working

**Comment by Justin-DynamicD** [comment]
is there a prerelease tag or similar we can use to download? I don't see a build associated with main at this time.

**Comment by cpanato** [comment]
> is there a prerelease tag or similar we can use to download? I don't see a build associated with main at this time.

we dont build and push main branch, but if that is the community want we can setup that 
for now you can clone and build yourself

**Comment by Justin-DynamicD** [comment]
> > is there a prerelease tag or similar we can use to download? I don't see a build associated with main at this time.
> 
> we dont build and push main branch, but if that is the community want we can setup that for now you can clone and build yourself

It's more of an ease of testing ask. Without a prerelease tag I have to clone, build, put into a custom container, then modify my existing pipelines to no longer download but instead leverage the installed version. In contrast I can just change the tag and test it if it were pre-tagged.

I'm assuming you branch per release so you can cherry pick and hotfix then?  I honestly didn't look at your branching strategy.

**Comment by Justin-DynamicD** [comment]
Quick update:

quick tests are promising, but most my pipelines use [chart releaser action](https://github.com/helm/chart-releaser-action) which has no way to use an existing version of cr (checking the code it _always_ downloads).  I would have to replace the action with a custom run step which then obfuscates testing (is cr having a problem or do I suck writing my own GHA steps?)

If you are capable of creating a pre-release version (i see its been done in the past) I can give it a more "real world" test, otherwise I can only do simple mocks.

**Comment by mijailr** [comment]
This is something I need as well. Has there been any progress on this?

**Comment by Justin-DynamicD** [comment]
I would love to have some better insight on the release process in general.  From what I can tell, this has been merged sense October, but going on 2 months later we still don`t have a release. What is the process for this and how can I help it along?

**Comment by cpanato** [comment]
@Justin-DynamicD needs more time as this is on my free time, also if you want to help, please review the PRs, triage issues, and submit any improvements that you might want to see

release is out: https://github.com/helm/chart-releaser/releases/tag/v1.7.0

will update the action in a few days

**Comment by Justin-DynamicD** [comment]
thank you very much for the update!

I was going to report that I have been running off the main branch all week without issue so the merge seems solid, but Ill happily switch to 1.7.0

**Comment by 0xThresh** [comment]
Hey @cpanato, any updates on when the action will be updated? I'm still seeing 1.6.0 as the latest option here: https://github.com/marketplace/actions/helm-chart-releaser

Thanks!

**Comment by cpanato** [comment]
@0xThresh will that today or early next week

**Pull request merged**
