### PR TITLE
Fixing registry client for packaging charts with OCI dependencies

### PR DESCRIPTION
**Pull request by bartlettc22**
Fixes: https://github.com/helm/chart-releaser/issues/225

### CODE REVIEW

**Comment by kingdonb** [comment]
Thank you for contributing this @bartlettc22 !

Can you rebase your commit with `--sign-off` so the DCO check goes away? I am not a reviewer, but I know this will be the first thing that needs update. I will test this change 👍

**Review by cpanato — COMMENTED** [review]
lgtm

can you sign the dco?

**Comment by kingdonb** [comment]
@cpanato can you kick off the remaining workflows now that DCO check is OK?

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
thanks!

**Pull request merged**
