### PR TITLE
accept generate_release_notes in github api upload to automatically g…

### PR DESCRIPTION
**Pull request by bukowa**
rebased in new PR beacuse i dont know git https://github.com/helm/chart-releaser/pull/219

### CODE REVIEW

**Comment by nikolaik** [comment]
This is wonderful! Is there anything holding back this PR?

**Comment by cpanato** [comment]
@bukowa i will rebase this PR to trigger CI

**Comment by cpanato** [comment]
> This is wonderful! Is there anything holding back this PR?

need to find a bit of time to test it

**Comment by bukowa** [comment]
> > @bukowa i will rebase this PR to trigger CI
> 
> ok, I dont have the permissions to push to your repo, please rebase the PR

Hey i resolved conflicts using github ui and gave you write permission to the repo just in case.

**Comment by cpanato** [comment]
> > > @bukowa i will rebase this PR to trigger CI
> > 
> > 
> > ok, I dont have the permissions to push to your repo, please rebase the PR
> 
> Hey i resolved conflicts using github ui and gave you write permission to the repo just in case.

thanks!
you don't need to give permission in your fork, in the PR there is an option to check and that grants permission for the PR


Screenshot 2023-01-04 at 17 31 02

**Review by cpanato — APPROVED** [review]
thanks

**Pull request merged**
