### PR TITLE
Prerelease option added

### PR DESCRIPTION
**Pull request by mguptahub**
Users have an option to mark as PreRelease=true when required. 

In my case, build from `main` branch is marked latest, v/s build from other branches are marked as `prerelease`

### CODE REVIEW

**Comment by mguptahub** [comment]
@cpanato - Can you help with reviewing this PR ?

**Comment by PrivatePuffin** [comment]
> @cpanato - Can you help with reviewing this PR ?

Dont expect much, they are basically AWOL and should be removed from the CNCF for that.

**Comment by cpanato** [comment]
Sorry for the delay, @mguptahub. I will take a look.

@PrivatePuffin I do those things in my free time and for free; if you want to help, please step up instead of complaining without knowing what happens behind the scenes

**Comment by cpanato** [comment]
@mguptahub can you rebase to get the latest changes and trigger ci?

**Comment by PrivatePuffin** [comment]
> @PrivatePuffin I do those things in my free time and for free; if you want to help, please step up instead of complaining without knowing what happens behind the scenes

You dont have to explain how opensource maintainership works. I am in the same situation and also dont have time to spend beyond the projects I'm already maintaining.

I'm indeed looking for some free time to spend on Helm for the last year or so.
Specifically, filing a formal request with the CNCF either step in and put their millions of funding to actually use or void the Helm CNCF status (like they did for OpenEBS already) and admit the CNCF is failing in keeping important cloud-infrastructure project alive.

**Comment by mguptahub** [comment]
@cpanato I was forced to create a new PR as could not reopen this PR #468 

Can you please look into it and suggest if any changes are required.

**Pull request closed without merging**
